# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c450eb1f8ce32ec22c73e310bcb4145ba31e87df7393a6cd16b9ab36df34c3319a9f17e216dd0aa8519f52b68bf53e9984922a0e7c3bb1440203f91792a518a

test:
  secret_key_base: 5641d4a8557b32bd2564fa5d413afb6899b898c53a630d4ce3ee4df81b71b738c77c489487fdd56381cfe6167a70db3ede33e470caeb1120a128c6d1204d88a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
